import { OutlineBtn } from "../components/Btn";

export const Agreement = () => {
  return (
    <>
      <div class="container-fluid px-5 my-5">
        <p>
          These Terms of Use ("Terms") govern the access or use by you, an
          individual or entity, from within any country in the world of
          applications, websites, content, products, and services made available
          by<b>&nbsp;WHITEWAVE CLOTHING Private Limited</b> , a private limited
          company established in India, having its registered office at
          <b>
            &nbsp;Tower A, 5 th Floor, 525 and 528 Spaze I-Tech Park (Sector 49,
            Sohna Road, Gurgaon, Haryana, Pincode – 122018) ("TECNOGEX").
          </b>
        </p>

        <p>
          This document is an electronic record in terms of Information
          Technology Act, 2000 of India and rules thereunder as applicable and
          the provisions pertaining to electronic records in various statutes as
          amended by the Information Technology Act, 2000. This electronic
          record is generated by a computer system and does not require any
          physical or digital signatures. By clicking on the "I ACCEPT" button,
          you are consenting to be bound by these Terms. PLEASE ENSURE THAT YOU
          READ AND UNDERSTAND ALL THESE TERMS BEFORE YOU USE THE SITE. If you do
          not accept any of the Terms, then please do not use the Site or avail
          any of the services being provided therein. YOUR AGREEMENT TO THESE
          TERMS SHALL OPERATE AS A BINDING AGREEMENT BETWEEN YOU AND TECNOGEX IN
          RESPECT OF THE USE AND SERVICES OF THE SITE. TECNOGEX may immediately
          terminate these Terms or any Services with respect to you, or
          generally cease offering or deny access to the Services or any portion
          thereof, at any time for any reason. Supplemental terms may apply to
          certain Services, such as policies for a particular event, activity or
          promotion, and such supplemental terms will be disclosed to you in
          connection with the applicable Services. Supplemental terms are in
          addition to, and shall be deemed a part of, the Terms for the purposes
          of the applicable Services. Supplemental terms shall prevail over
          these Terms in the event of a conflict with respect to the applicable
          Services. TECNOGEX may amend the Terms related to the Services from
          time to time. Amendments will be effective upon TECNOGEX's posting of
          such updated Terms at this location or the amended policies or
          supplemental terms on the applicable Service. Your continued access or
          use of the Services after such posting constitutes your consent to be
          bound by the Terms, as amended.
        </p>

        <p>
          Your acceptance of the Terms shall be deemed to include your
          acceptance of the privacy policy available at
          <a href="https://www.tecnogex.com" target="neewq">
            {" "}
            https://www.tecnogex.com
          </a>
        </p>
      </div>
      <div class=" container-fluid px-5 my-5">
        <div class="agreementhead text-center">
          <h2 style={{ color: " rgb(75, 75, 241)" }}>
            TECNOGEX SERVICE LEVEL AGREEMENT FOR MERCHANT(S)
          </h2>
        </div>

        <div class="agreementbody mt-5">
          <p>
            <b>WHITEWAVE CLOTHING Private Limited</b> having registered address
            at
            <b>
              Tower A, 5 th Floor, 525 and 528 Spaze I-Tech Park (Sector 49,
              Sohna Road, Gurgaon, Haryana, Pincode – 122018) ("TECNOGEX")
            </b>
            and
            <input class="agreementinput" type="text" name="add2input" /> (legal
            name of MERCHANT]&ZeroWidthSpace; (in short the “MERCHANT”),
            mutually agree to the terms and conditions which are incorporated
            into this agreement as of <b>[ insert current date]</b>
            &ZeroWidthSpace;:
            <input class="agreementinput" type="date" name="date" />
          </p>
          <h5>A. Definition or meanings</h5>
          <p>
            (a) Merchant: Means and includes individual or legal entity who
            enters the present agreement with TECNOGEX to provide and perform
            LAUNDRY AND DRY-CLEANING services including any derivative,
            replacement and follow-on services thereto. <br />
            (b) Customer : Means and includes individual or legal entity who
            avails or wishes to avails LAUNDRY AND DRY-CLEANING services
            including any derivative, replacement and follow-on services. <br />
            (c) LAUNDRY AND DRY-CLEANING services offered: Means and includes
            LAUNDRY AND DRY- CLEANING services including any derivative,
            replacement and follow-on services offered by the Merchant through
            the Mobile Applications/Website of TECNOGEX. <br />
          </p>
          <h5 class="mt-5">1. Agreement Overview</h5>
          <p>
            <b>1.1.</b> &nbsp; TECNOGEX hereby retains the MERCHANT to provide
            and perform LAUNDRY AND DRY- CLEANING services including any
            derivative, replacement and follow-on services thereto (the
            “Services”) on the representation of the Merchant that the Merchant
            is engaged in the business of LAUNDRY AND DRY-CLEANING services.
          </p>
          <p>
            <b>1.2.</b> &nbsp; This agreement represents a service level
            agreement between TECNOGEX and the MERCHANT for the provision of the
            Services of LAUNDRY AND DRY-CLEANING and related works.
          </p>
          <p>
            <b>1.3.</b> &nbsp; Any additional or future services that the
            parties agree shall be subject to this Agreement.
          </p>
          <h5 class="mt-5">2. Service Agreement</h5>
          <p>
            <b>2.1.</b> &nbsp; The following detailed service parameters are the
            responsibility of the MERCHANT in the ongoing support of this
            Agreement:
          </p>
          <p>
            (a) to mutually agree with TECNOGEX on catalogue of LAUNDRY AND
            DRY-CLEANING services, Price list related to LAUNDRY AND
            DRY-CLEANING services, cost to TECNOGEX, and LAUNDRY AND
            DRY-CLEANING services pricing at the MERCHANT’s physical location,
            all of which may be changed from time to time if mutually agreed
            upon by the parties;
            <br />
            (b) to work with TECNOGEX to setup the ability to receive orders, to
            confirm the ability to fulfil orders, to notify TECNOGEX
            immediately, to fulfil and have complete orders, to label and
            package all orders/deliveries via mobile APPLICATIONS, website,
            emails, or any other modes as prescribed by the TECNOGEX from time
            to time.
          </p>
          <p></p>
          <p>
            <b>2.2.</b> &nbsp; The following detailed service parameters are the
            responsibility of TECNOGEX in the ongoing support of this Agreement:
          </p>
          <p>
            (a) to send orders via email/mobile Application to the MERCHANT;
            <br />
            (b) to use reasonable efforts to make advise the MERCHANT quickly of
            any changes to orders that have been confirmed; <br />
          </p>
          <p></p>
          <h5 class="mt-5">3. Pricing &amp; Payment</h5>
          <p>
            <b>3.1.</b> &nbsp; MERCHANT agrees to pay onboarding fee of Rs.
            <input
              class="agreementinput mx-2"
              type="text"
              name="totalfeeinput"
            />
            to the TECNOGEX, and MERCHANT has opted one of the below schedules
            offered by the TECNOGEX to the Merchants. To specify and acknowledge
            his consent with respect to opted schedule, the Merchant has signed
            hereunder:
          </p>
          <div id="addonservice-cart" class="cartsection">
            <div class="table-responsive  text-center">
              <table class="table table-bordered ">
                <thead>
                  <tr>
                    <th class="">Sr. No.</th>
                    <th colspan="15">
                      Merchant agrees to pay the onboarding fee as per one of
                      the below-mentioned schedules :
                    </th>
                    <th class="text-center">Consented by the Merchant</th>
                  </tr>
                </thead>
                <tbody>
                  <tr id="cartaddon-row0">
                    <td class=" font-weight-bold">1.</td>
                    <td colspan="15">
                      At the time of signing of this agreement
                    </td>
                    <td class=" my-2">
                      <div class="d-flex justify-content-around align-items-center">
                        <div class="form-check pl-0">
                          <input type="radio" name="onboardagree" value="0" />
                          <label for="yesboardopt">Yes</label>
                        </div>

                        <div class="form-check">
                          <input type="radio" name="onboardagree" value="0" />
                          <label for="noboardopt">No</label>
                        </div>
                      </div>
                    </td>
                  </tr>

                  <tr id="cartaddon-row1">
                    <td class="cartservice font-weight-bold">2.</td>
                    <td colspan="15">
                      Onboarding fees shall be deducted from the commission due
                      to the merchant, and <br /> if you choose this option
                      commission will be increased by 2%.
                    </td>
                    <td class="text-center">
                      <input
                        class="agreementinput"
                        type="text"
                        name="onboardfee1input"
                      />
                    </td>
                  </tr>
                </tbody>
              </table>

              <div class="table-responsive cartsection text-center">
                <table class="table table-bordered ">
                  <thead>
                    <tr>
                      <th class="">Sr. No.</th>
                      <th colspan="15">Commision Agreement</th>
                      <th class="text-center">Commission % </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr id="cartaddon-row0">
                      <td class=" font-weight-bold" colspan="15">
                        1.
                      </td>
                      <td>The merchant shall agree to this commission %</td>
                      <td class="text-center">
                        <input
                          class="agreementinput form-control"
                          type="text"
                          name="commissioninput"
                        />
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <p>
              TECNOGEX shall have all the rights related to change and
              modification in the fee and to charge an additional fee at any
              point in time.
            </p>
          </div>
          <p>
            <b>3.2.</b> &nbsp; The merchant agrees that&nbsp;TECNOGEX&nbsp;will
            collect payment on behalf of the merchant for the services provided
            by the Merchant.
          </p>
          <p>
            <b>3.3.</b> &nbsp; Merchant agrees that&nbsp;the merchant shall be
            liable to pay commission to the TECNOGEX&nbsp;with respect to
            payment received by the Merchant for the services and at the same
            time, Merchant also agrees that the TECNOGEX may in alternate deduct
            in ts commission from the payment to be made to the merchant.
          </p>
          <p>
            <b>3.4.</b> &nbsp; The Merchant agrees that&nbsp;TECNOGEX&nbsp;will
            make payment to the merchant for the services provided by the
            Merchant after deducting its commission and other charges as agreed
            from time to time.
          </p>
          <p>
            <b>3.5.</b> &nbsp; Payment settlement period : <br />
            The payment will be cleared to the Merchant into two parts i.e.;
            orders from (Monday to Thursday) will be settled on coming Tuesday
            and Friday to Sunday will be settled on coming Thursday, subject to
            deduction of TDS and other applicable charges.
          </p>
          <h5 class="mt-5">4. Errors and penalties</h5>
          <p>
            <b>4.1.</b> &nbsp; TECNOGEX reserves the right to determine, within
            reason, appropriate compensation for errors made by the MERCHANT in
            the fulfillment of services/orders. The MERCHANT agrees that the
            costs associated with rectifying such errors are the sole
            responsibility of the MERCHANT.
          </p>
          <p>
            <b>4.2.</b> &nbsp; Errors and penalties include, but are not limited
            to, the following:
          </p>
          <p>
            (a) Order cancellation charges : <br />
            &nbsp; &nbsp; (i) If an order is canceled by the merchant
            (applicable post pick up scheduled) The merchant will be penalized
            by the Cancellation fee (pick-up charge + Administration charge)
            which shall be an adjustment from his due payment. After
            cancellation of the order by the merchant 2 times, TECNOGEX reserves
            the right to terminate the agreement without any further notice.
            <br />
            (b)
            <b>
              If service delivery time is missed by Merchant, as determined by
              TECNOGEX in its sole discretion, the TECNOGEX shall be entitled to
              impose penalty on the merchant as per following schedule:
            </b>
            <br />
            <b>Delay in delivery: (Reasonable/Unreasonable Ground)</b>
            <br />
            By the merchant: <br />
            &nbsp; &nbsp; (i) Less than 4 Hours&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5%
            of the order value
            <br />
            &nbsp; &nbsp; (ii) 4 &lt; 8
            Hours&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;10
            % of the order value <br />
            &nbsp; &nbsp; (iii) More than 8 hours&nbsp;&nbsp;&nbsp;&nbsp;15% of
            the order value
            <br />
            (c) <b> If the Product is lost and damaged:</b> <br />
            It the produce is lost/damaged by the Merchant
            <b>
              the TECNOGEX shall be entitled to impose penalty on the merchant
              as per following schedule
            </b>
            <br />
            <b>Loss and damage of the items: (By the merchant)</b>
            <br />
            <br />
            <b>
              <u>If the item/s is more than 6 months old</u>
            </b>
            <u> </u> <br />
            <br />
            <b>(a) 40% of the bill produced by the user</b> <br />
            <b>(b) Current market price</b> <br />
            <b>
              (c) 10 times of the service of the invoice generated. <br />
              (Whichever is less)
            </b>
            <br /> <br />
            <b>If the item/s is less than 6 months old</b> <br />
            <br />
            <b>(a) 100% of the bill produced by the user</b> <br />
            <b>(b) Current market price</b> <br />
            <b>
              (c) 10 times of the service of the invoice generated. (Whichever
              is less)
            </b>
            <br />
          </p>
          <p>
            Merchant shall be liable to pay the amount as per the above
            schedule. TECNOGEX shall have all the rights to deduct the amount in
            5 installments from the payment made to the Merchant.
          </p>
          (d) If the Merchant commits two (2) or more errors in a given 30-day
          period, TECNOGEX reserves the right to terminate this Agreement
          immediately. The final payment to the Merchant will be calculated
          based on the amount of penalty or other deductions to be made from the
          due amount of payment to the Merchant. <br />
          <p></p>
          <p></p>
          <h5 class="mt-5">
            5. Merchant undertaking regarding the compliance of Laws
          </h5>
          <p>
            The MERCHANT assures the TECNOGEX that it has taken all the licenses
            applicable to its business. MERCHANT agrees that the Merchant will
            not provide or deliver any item or services that may be unsafe,
            harmful, misbranded, or substandard or which contains extraneous
            matter or is not environment friendly. The Merchant agrees that
            violating these standards will be grounds for immediate termination
            of this Agreement by TECNOGEX, as well as for action by TECNOGEX
            against the Merchant for damages. TECNOGEX will not be held
            responsible in any manner whatsoever for the non-compliance at the
            merchant’s end.
          </p>
          <h5 class="mt-5">6. Miscellaneous</h5>
          <p>
            <b>6.1.</b> &nbsp; Nothing in this Agreement will constitute a
            commitment by TECNOGEX to send to the Merchant any particular volume
            or quantity of orders.
          </p>
          <p>
            <b>6.2.</b> &nbsp; Nothing in this Agreement shall preclude TECNOGEX
            from obtaining services similar to the Services from third parties.
          </p>
          <h5 class="mt-5">7. Additional Terms and Conditions</h5>
          <p>
            TECNOGEX and The Merchant mutually agree to the following additional
            terms and conditions. :
          </p>
          <p>
            <b>
              7.1. &nbsp; Intellectual Property Rights and Confidential
              Information
            </b>
          </p>
          <p>
            (i) TECNOGEX shall own and retain all right, title, and interest to
            its intellectual property, whether registered or not, including
            patents, inventions (whether or not patentable), trademarks, trade
            names, service marks, copyrights, software, source code, and any
            registrations and applications for registration of any of the
            foregoing and confidential and proprietary information including
            trade secrets. <br />
            (ii) For the purposes of this Agreement,
            “&ZeroWidthSpace;Confidential Information”&ZeroWidthSpace; means any
            and all material and information of TECNOGEX or TECNOGEX customers,
            including any personal information and any information, whether
            recorded in a material form or not, about or related to an
            identifiable person, including an individual who can be identified
            directly or indirectly from the information, and in the case of
            TECNOGEX includes all such information of TECNOGEX and TECNOGEX
            affiliates relating to its or their respective customers, clients,
            clients’ customers, suppliers, partners, and their employees and
            contractors, which has or will come into the possession or knowledge
            of the Merchant in connection with or as a result of entering into
            this Agreement or performance of the Services. <br />
            (iii) The Merchant acknowledges that all Confidential Information
            consists of confidential and proprietary information. Except as
            required by law, rule, regulation, or court order the Merchant
            agrees to keep all Confidential Information in strict confidence.
            The Merchant represents, warrants and covenants that it will comply
            with applicable Indian data protection laws and
            regulations&ZeroWidthSpace; and all "substantially similar"
            legislation that applies to Services under this Agreement. <br />
            (iv) Upon the termination or expiry of this Agreement, the Merchant
            will return to TECNOGEX all Confidential Information which is then
            in the Merchant’s possession or control, and will remove all digital
            representations thereof in any form from all electronic storage
            media in its possession or under its control. <br />
          </p>
          <p>
            <b>7.2. &nbsp; Non-Competition</b>
          </p>
          <p>
            (i) Merchant covenants that in no event shall it, or any of its
            affiliates, during the term of this Agreement or for a period of 5
            year thereafter: : <br />
            &nbsp; &nbsp; (a) Solicit, on behalf of the Merchant or otherwise,
            through the use of Confidential Information or otherwise, any client
            of TECNOGEX; or
            <br />
            (ii) The Merchant agrees and acknowledges that any breach by it of
            its obligations and duties under this Section shall result in
            immediate and irreparable harm and damage to TECNOGEX for which
            monetary damages alone will not fairly or adequately compensate
            TECNOGEX or otherwise remedy such breach. Accordingly, the Merchant
            agrees that it shall not oppose or otherwise interfere with any
            applications by TECNOGEX to a court of competent jurisdiction for
            any equitable relief or remedy associated with any such breach of
            this Agreement. Both parties agree and acknowledge that this Section
            is fair and reasonable in the commercial circumstances of this
            Agreement and that each party's agreements in this Section have been
            a material inducement and promise by each party upon which both
            parties have relied, and been induced, to enter into this Agreement.
            <br />
          </p>
          <p></p>
          <p>
            <b>7.3. &nbsp; Indemnities</b>
          </p>
          <p>
            Notwithstanding any other provision hereof, the Merchant agrees to
            indemnify TECNOGEX and its respective directors, officers, and
            employees from and against all losses, costs, damages, expenses, and
            liabilities (including reasonable legal fees) which may be suffered
            or incurred by TECNOGEX arising out of or as a result of or relating
            in any manner whatsoever to:
          </p>
          <p>
            (i) Any breach of a representation, warranty, or covenant made by
            the Merchant in this Agreement; <br />
            (ii) Any injury to persons (including injuries resulting in death)
            or loss of or damage to property of others which may be or be
            alleged to be caused by or suffered as a result of or in connection
            with the performance by the Merchant or its representatives of all
            or any part of the Merchant’s obligations under this Agreement;
            <br />
            (iii) The negligence or wilful misconduct of the Merchant and/or its
            representatives in the performance of the Merchant’s obligations
            under this Agreement; and
            <br />
            (iv) Any breach of applicable law by the Merchant and/or its
            representatives in the performance of the Merchant’s obligations
            under this Agreement. <br />
          </p>
          <p></p>
          <p>
            <b>7.4. &nbsp; Limitation of Liability</b>
          </p>
          <p>
            Under no circumstances shall either party have any liability,
            whether in contract or for negligence or otherwise and whether
            related to any single event or series of connected events, for any
            incidental, indirect, or consequential damages or loss of profits,
            loss of business, revenue or anticipated savings or other economic
            loss arising out of or in furtherance of the provisions or
            objectives of this Agreement whether or not the party was informed
            or was aware of the possibility of such loss.
          </p>
          <p></p>
          <p>
            <b>7.5.</b> &nbsp;
            <b>
              The effective date of onboarding will the date of signing the LOU.
              (Mode will be Virtual or physical)
            </b>
          </p>
          <p>
            <b>7.6. &nbsp; Termination</b>
          </p>
          <p>
            Either party shall have the right to terminate all or any part of
            this Agreement by giving the other party 30 days' written notice.
          </p>
          <p></p>
          <p>
            <b>7.7. &nbsp; Effect of Termination</b>
          </p>
          <p>
            If this Agreement is terminated, TECNOGEX may invoice the Merchant
            for Services performed up to the date of termination of the
            Agreement. (After 30 days of termination of this agreement)
          </p>
          <p></p>
          <p>
            <b>7.8. &nbsp; Severability</b>
          </p>
          <p>
            The invalidity or unenforceability of any particular provision of
            this Agreement will not affect or limit the validity or
            enforceability of its remaining provisions.
          </p>
          <p></p>
          <p>
            <b>7.9. &nbsp; Survival</b>
          </p>
          <p>
            Any provision of the Agreement that contemplates performance or
            observance subsequent to termination or expiration of the Agreement
            will survive termination or expiration of the Agreement and will
            continue in full force and effect, including, but not limited to,
            those relating to confidentiality, proprietary rights, warranties,
            indemnification, and limitation of liability, non- solicitation,
            non-competition, and dispute resolution.
          </p>
          <p></p>
          <p>
            <b>7.10.</b> &nbsp; Binding Effect and Assignment
          </p>
          <p>
            This Agreement shall be binding upon and shall enure to the benefit
            of and be enforceable by each of the parties, their respective
            successors, and permitted assigns. This Agreement may not be
            assigned by the Merchant. All or part of this Agreement may be
            assigned by TECNOGEX to any person who acquires all or part of
            TECNOGEX’s business and such assignee may enforce this Agreement as
            if such assignee was a party hereto.
          </p>
          <p></p>
          <p>
            <b>7.11. &nbsp; Independent Contractors</b>
          </p>
          <p>
            The Merchant will provide all services as an independent contractor
            and in no way will the Merchant or its employees be considered
            employees, agents, partners, fiduciaries, or joint venturers of
            TECNOGEX. The Merchant and its employees will have no authority to
            represent TECNOGEX or its affiliates without TECNOGEX’s permission
            or bind TECNOGEX or its affiliates in any way, and the Merchant
            agrees that neither the Merchant nor its employees will hold
            themselves out as having authority to act for TECNOGEX or its
            affiliates.
          </p>
          <p></p>
          <p>
            <b>7.12. &nbsp; Governing Law</b>
          </p>
          <p>
            This Agreement is governed by and is to be interpreted, construed,
            and enforced in accordance with the laws of India.
          </p>
          <p></p>
          <p>
            <b>7.13. &nbsp; Jurisdiction / Arbitration</b>
          </p>
          <p>
            This Agreement is governed by, and is to be interpreted, construed,
            and enforced in accordance with the laws of India.
          </p>
          <p>
            (i) Jurisdiction: <br />
            Subject to the provisions of Clause 7.13 (ii) below, It has been
            agreed between the parties hereto that only the Court of competent
            jurisdiction at New Delhi shall have exclusive jurisdiction with
            respect to any suit, action, or any other proceedings relating to
            this Agreement. <br />
            (ii) Arbitration: <br />
            &nbsp; &nbsp; (a) If any dispute or difference arises between the
            Parties hereto during the subsistence of this Agreement or
            thereafter, in connection with the validity, interpretation,
            termination, implementation, or alleged breach of any provision of
            this Agreement or regarding any question relating hereto the Parties
            hereto shall endeavor to settle such dispute or difference amicably.
            If they are unable to agree to an amicable solution to the dispute
            or difference within 30 (thirty) days, from rising of the dispute or
            difference, such dispute or difference shall be decided by a sole
            Arbitrator appointed by TECNOGEX. The cost of "arbitration shall be
            borne by the VENDOR. <br />
            &nbsp; &nbsp; (b) The arbitration proceedings shall be governed by
            the provisions of (Indian) Arbitration and Conciliation Act, 1996.
            The seat and venue of arbitration shall be New Delhi.&nbsp; The
            proceedings of arbitration shall be in the English language."
            <em>
              The arbitration award shall be final and binding on the parties.”
            </em>
          </p>
          <p>
            <b>7.14. &nbsp; Modification and Waiver</b>
          </p>
          <p>
            No waiver of satisfaction of a condition, non-performance of an
            obligation, or modification of any provision under this Agreement
            shall be effective unless it is in writing and signed by the party
            granting the waiver. No waiver under this section affects the
            exercise of any other rights under this Agreement.
          </p>
          <p></p>
          <p></p>
          <h5 class="mt-5">8. Branding Guidelines</h5>
          <p>
            The Merchant agrees to the following additional terms and
            conditions, regarding TECNOGEX’s brand standards.
          </p>
          <p>
            <b>8.1. &nbsp; Presentation &amp; Labelling</b>
          </p>
          <p>
            All packaging, PACKETS/BAGS, labels must comply the policy and
            direction of the TECNOGEX given to the Merchant from time to time in
            that regard.
          </p>
          <h5 class="mt-5">9. Cross-Marketing and Promotional Activities</h5>
          <p>
            The Merchant agrees to work with TECNOGEX to use commercially
            reasonable efforts to engage in the following cross-marketing and
            promotional activities:
          </p>
          <p>
            (1) Social media engagement; <br />
            (2) Guest blog features; <br />
            (3) Testimonials; <br />
            (4) MERCHANT video features; <br />
            (5) Online promotion of TECNOGEX’s LAUNDRY AND DRY-CLEANING services
            via a link to TECNOGEX’s website or a picture of the TECNOGEX logo;
            and
            <br />
            (6) Partnering with and/or sponsoring TECNOGEX at key annual events.{" "}
            <br />
            (7) TECNOGEX shall be entitled to charge Marketing fee and other
            charges (customer support charges) from the Merchant.(Unclear)
            <br />
          </p>
          <p></p>
          <h5 class="mt-5">
            10. List of documents required to onboard a Merchant on platform.
          </h5>
          <p>
            The Merchant is under obligation to provide following documents to
            the TECNOGEX, failing which this agreement shall be treated as null
            and void and the Merchant shall indemnity the loss suffered by the
            TECNOGEX
          </p>
          <p>
            (1) Trade License, as per Shop and Establishment Act (MSME) <br />
            (2) GSTIN or Declaration in respect of GST <br />
            (3) Cancelled cheque or Passbook for banking details <br />
            (4) Basic KYC documents (Aadhar, Pan, voter ID, Passport, etc.)
            <br />
          </p>
          <h5 class="mt-5 ">11. TAXES </h5>
          <p>
            The transactions are bilateral between the Merchant and Customer,
            and therefore, TECNOGEX shall not be liable to charge or deposit any
            taxes applicable on such transactions.
          </p>
          <p>
            TECNOGEX and the Merchant each agree that they have read,
            understood, and agree to the Standards of Service set out in this
            Agreement.
          </p>
        </div>

        <div class="agreementfootsign mt-sm-5 pt-5">
          <h4>TECNOGEX</h4>

          <p>
            <b>
              By:
              <input class="agreementinput" type="text" name="signfeeinput" />
            </b>
          </p>
          <p>Title Date: _____</p>
        </div>
        <div class="agreementfootsign">
          <h4>[NTD: insert legal name of MERCHANT]</h4>
          <p>
            <b>
              By:
              <input class="agreementinput" type="text" name="signfeeinput" />
            </b>
          </p>
          <p>Title Date: _____</p>
        </div>
      </div>
      <div className="Agreement_btn_div">
        <OutlineBtn title="submit" />
      </div>
    </>
  );
};
